# Generated by Django 4.0.4 on 2022-05-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('country', models.CharField(max_length=40, verbose_name='Country')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('minimum_salary', models.IntegerField(verbose_name='Minimum salary')),
                ('maximum_salary', models.IntegerField(verbose_name='Maximum salary')),
                ('publication_time', models.DateTimeField(verbose_name='Publication time')),
                ('description', models.TextField(max_length=250, verbose_name='Description')),
                ('owner', models.CharField(max_length=70, verbose_name='Owner')),
            ],
        ),
    ]
