# Generated by Django 4.0.4 on 2022-05-28 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(default=django.utils.timezone.now, max_length=3, verbose_name='Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photos/%Y/%m/%d/', verbose_name='Image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='requirements',
            field=models.TextField(default=django.utils.timezone.now, max_length=150, verbose_name='Requirements'),
            preserve_default=False,
        ),
    ]
