# Generated by Django 4.0.4 on 2022-05-28 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_vacancy_options_vacancy_currency_vacancy_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='publication_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publication time'),
        ),
    ]
