# Generated by Django 4.0.4 on 2022-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_vacancy_publication_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='maximum_salary',
            field=models.IntegerField(blank=True, verbose_name='Maximum salary'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='minimum_salary',
            field=models.IntegerField(blank=True, verbose_name='Minimum salary'),
        ),
    ]
