# Generated by Django 4.0.4 on 2022-06-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_vacancy_maximum_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='maximum_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum salary'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='minimum_salary',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum salary'),
        ),
    ]
