# Generated by Django 4.0.4 on 2022-06-15 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacancy',
            new_name='News',
        ),
    ]
